// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2B6cIsUcsJUVAlR-4dBqnkr-3IIQUnEc',
    appId: '1:288778597965:web:022664d41cad6b4977ce04',
    messagingSenderId: '288778597965',
    projectId: 'lab8-6ecc7',
    authDomain: 'lab8-6ecc7.firebaseapp.com',
    databaseURL: 'https://lab8-6ecc7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lab8-6ecc7.firebasestorage.app',
    measurementId: 'G-L4CY9QQHXH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnY1QKOTWnGBzlQyU7_UPYhM49qRCN8L8',
    appId: '1:288778597965:android:ef93abd6803a427e77ce04',
    messagingSenderId: '288778597965',
    projectId: 'lab8-6ecc7',
    databaseURL: 'https://lab8-6ecc7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lab8-6ecc7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl5BPtRYoCH4DqAeYtLNL2-nanN2bPFp4',
    appId: '1:288778597965:ios:00c34b02933bbe8077ce04',
    messagingSenderId: '288778597965',
    projectId: 'lab8-6ecc7',
    databaseURL: 'https://lab8-6ecc7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lab8-6ecc7.firebasestorage.app',
    iosBundleId: 'com.example.lab8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAl5BPtRYoCH4DqAeYtLNL2-nanN2bPFp4',
    appId: '1:288778597965:ios:00c34b02933bbe8077ce04',
    messagingSenderId: '288778597965',
    projectId: 'lab8-6ecc7',
    databaseURL: 'https://lab8-6ecc7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lab8-6ecc7.firebasestorage.app',
    iosBundleId: 'com.example.lab8',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2B6cIsUcsJUVAlR-4dBqnkr-3IIQUnEc',
    appId: '1:288778597965:web:535919533bba878977ce04',
    messagingSenderId: '288778597965',
    projectId: 'lab8-6ecc7',
    authDomain: 'lab8-6ecc7.firebaseapp.com',
    databaseURL: 'https://lab8-6ecc7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lab8-6ecc7.firebasestorage.app',
    measurementId: 'G-8VJ4SBBEJH',
  );
}
